name: GitHub Actions Demo
on: 
  push:
    branches: 
     - 'main'
    paths-ignore: [.github/**]
  pull_request:
    branches: 
     - 'main'  
  schedule:
    - cron: "15 6 * * 0" 
  workflow_dispatch:
    inputs: 
      environmentsLabel:
        description: environment to run in
        type: environment
        required: true
    

run-name: "Build"
jobs:
  Build123:
    runs-on: ubuntu-latest
    steps:
      - name: Event that triggered the build
        run: |
          echo "person triggering build ${{github.event_name}}"
          echo "name of branch ${{github.ref }} "
      - name: "checkout"
        uses: actions/checkout@v4.2.2

      - name: list files in repo
        run: |
          echo "repo ${{github.repository }} contains files"
          tree
  Test1:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build123
    steps:
      - name: test
        run: echo "Testing..."
    environment: Test
  LoadTest:
    runs-on: ubuntu-latest
    environment: Load-test
    needs: Build123
    steps:
      - name: test
        run: |
          echo "Load Testing..."
          sleep 10
          echo "done"
  Production:
    runs-on: ubuntu-latest
    if: github.inputs.environmentsLabel == 'production'
    environment: 
      name: production
      url: 'https://writeabout.net'
    needs: [ Test1, LoadTest ]
    steps:
      - name: deploy1
        run: |
          echo "deploying"
          sleep 10
          echo "done"
      - name: deploy2
        run: |
          echo "deploying..."
          sleep 10
          echo "done"
  


